### ISSUE TITLE
[Web Bug]: Landscape videos are getting shrunk down

### ISSUE THREAD

**Issue by XanatosX** [joinloops/loops-server#241]
### Description

I noticed that with some update in the past, if you upload a full HD landscape video to Loops it is getting shrunk down for the web UI. This does make it hard to view them on the web fronted.

For example my first uploaded video was just fine as you can see here:

https://loops.video/v/bFkx_XCV69

But if changed, now they look like that:

https://loops.video/v/cho38e6Cdo
https://loops.video/v/czhlmDbIBc

This does make the service quite unusable for me as I mostly do use landscape videos.

### Steps to reproduce

1. Open Web UI
2. Click to upload new video
3. Upload a Full HD Landscape video
4. Preview is fine
5. Press upload
6. Video is getting shrunk on the web ui, making it nearly unviewable

### Loops version

v1.0.0-beta.6

### Acknowledgements

Yes

**Comment by XanatosX** [comment]
Okay I did discover more about this issue. It is properly something with the video player size if a loop is shared as a link.

So if those videos are shown in the feed they do look "normal" as the UI around it reflects a portrait like view and the player does match that exactly. If you copy the link to a video and open it up on a full HD monitor the space for the video is much larger than in the feed. This does make it feel like the video is super small while still being the same size as in the feed.

<img width="1913" height="945" alt="Image" src="https://github.com/user-attachments/assets/65ebafcb-6369-45a7-ba31-76b13d4562bf" />
> Viewed as "link"

<img width="1918" height="1028" alt="Image" src="https://github.com/user-attachments/assets/6028450a-a802-4f29-af46-4286fffb11af" />
> Viewed in feed

Size stays identically but looks much smaller if shared as a link. In my opinion the player should use all space available if in the "link" share mode, if the video is landscape.

Maybe add a flag on upload to define if a video is landscape or detect automatically based on the video ratio if possible. If it is landscape make the player "fullscreen" on the link share version.

**Comment by dansup** [comment]
@XanatosX As you can see here https://loops.video/v/c-hN0o39KO the landscape support has been fixed!

**Comment by XanatosX** [comment]
Okay I have seen a lot of landscape videos on the platform but if I reupload the one from yesterday it's not working.

I will try to render that once again, might be some kind of logic to prevent duplicate uploads to be reprocessed.

**Comment by XanatosX** [comment]
Hmm did create a new file and it's still not working as it should:

https://loops.video/v/c-jsgpe8Ld

I do create such files with "kdenlive" but they are indeed listed as 1920x1080 so this should be a fine landscape video.

The format is mp4. Upload is done via the web interface.

https://github.com/user-attachments/assets/dd913e43-879c-4129-9af4-9d620071a90c
>Raw Video for testing purpose

**Comment by dansup** [comment]
> Hmm did create a new file and it's still not working as it should:
> 
> https://loops.video/v/c-jsgpe8Ld
> 
> I do create such files with "kdenlive" but they are indeed listed as 1920x1080 so this should be a fine landscape video.
> 
> The format is mp4. Upload is done via the web interface.
> 
>  godot_game_console_autocomplete_arguments_reupload.mp4 
> > Raw Video for testing purpose

Can you clear your browser cache and force refresh and try again?

**Comment by XanatosX** [comment]
I deleted all storage and cache relevant data from within the browser (Zen, a Firefox fork) and uploaded the video once again. As I needed to login again, the deletion seemed to work. I think the browser shouldn't be the issue as that part of code converting the video is run on server side, right?

https://loops.video/v/c-mQOF6RMd

From a private browser instance

https://loops.video/v/c-nbYqZgMk

https://github.com/user-attachments/assets/cef0f3f7-84bb-4601-a742-2ddfa646fedb
>Video from first uploaded video

**Comment by XanatosX** [comment]
I also did open it up in Edge and the video is still in that small format on my side.

<img width="1915" height="988" alt="Image" src="https://github.com/user-attachments/assets/c5b61d96-83c3-40f8-9465-5b2a463cfff9" />

So seems like this is not fixed just yet.

**Comment by dansup** [comment]
> https://loops.video/v/c-rh6e_5N7
> 
> Seems like it's also wrong if uploaded via Edge. I'm confused as I have seen a lot of those videos formatted correctly already. So maybe something with the video itself?
> 
> Is kdenlive doing something strange?
> 
> <img alt="Image" width="333" height="226" src="https://private-user-images.githubusercontent.com/10531466/531461212-dd2ac7e0-27e1-4a79-858e-8ce11bcdcfdb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjczNTUxNDUsIm5iZiI6MTc2NzM1NDg0NSwicGF0aCI6Ii8xMDUzMTQ2Ni81MzE0NjEyMTItZGQyYWM3ZTAtMjdlMS00YTc5LTg1OGUtOGNlMTFiY2RjZmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTAyVDExNTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MGUyYWNjYWQ3YWZlZmRjOTM1YTQ4OTE4YTU4ZTI1ZGJlZGIxYjI3YjM0YzE1ZjI0ZjYyNGFhZTU5N2QwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._kinO9r3KyAexShM8TxA1R5zFIrYA4scD-dNUO5sy9M">
> the lines are reading like that from top to bottom:
> 
> * Length
> * Width
> * Height
> * Data rate
> * Total bit rate
> * Single bit rate
> * Bit rate
> * Channels
> * Sampling rate
> 
> There is the raw video to download (24 hours available 1 download)
> 
> https://wormhole.app/NJlz8b#5P2n5dVsUO6xI4ObiKEWZg

Yeah this is most likely browser related, I can successfully upload that video in landscape mode https://loops.video/v/c-sb9jXqNi

**Comment by XanatosX** [comment]
The upload did work in the past

https://loops.video/v/bFVrP5Ctmq

So there was a time where this was working. Back then I already did use Zen.

**Comment by dansup** [comment]
@XanatosX I just uploaded another Landscape video without a problem https://loops.video/v/c-EO2-bNPY 

Can you try uploading a video with the Chrome browser?

**Comment by XanatosX** [comment]
Nope restart didn't fix it:

<img width="1915" height="89" alt="Image" src="https://github.com/user-attachments/assets/953d608d-2a9d-4507-bc7b-15ddfcbf42a0" />

Tried with both instances of the video -.- The interesting part is that it is getting identified correctly as "landscape" but then the size is flipped.

**Comment by XanatosX** [comment]
I tried multiple videos and that wrong orientation issue seems to be there for every browser (Firefox, Zen or Edge) I use.
This is really confusing as it is getting detected correctly as "landscape" before. Not sure why it does react like that.

This does not happen on Arch Linux with Zen, making it even stranger ...

**Comment by dansup** [comment]
This has been fixed!
